In [26]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import gc
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression, ElasticNet
from sklearn.model_selection import train_test_split
from sklearn.svm import SVR
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    root_mean_squared_error,
    r2_score,
    mean_absolute_percentage_error,
    median_absolute_error,
    explained_variance_score,
)
from xgboost import XGBRegressor

In [27]:
df = pd.read_parquet("data/train.parquet", engine="pyarrow")
df

,payload,total_distance_m,wind_speed_mean,wind_speed_std,wind_x_mean,wind_y_mean,velocity_mag_mean,velocity_mag_max,acceleration_mag_mean,acceleration_mag_std,battery_needed
0,0.0,76.894875,3.898058,1.952675,0.973186,-1.246141,2.676774,6.261616,9.842870,0.466372,1000.743935
1,0.0,125.616211,3.522941,2.159456,0.088843,-1.886357,2.387432,7.676739,9.881874,0.628406,1205.255874
2,0.0,71.228093,4.581182,3.335733,-0.696895,-1.778235,3.110644,7.213987,9.902090,0.545290,789.073853
3,0.0,78.000098,4.596319,3.438072,-0.351732,-1.389653,3.165734,9.425537,9.900368,0.559073,687.813976
4,0.0,71.103672,3.333910,2.247522,0.062744,-1.257258,2.126439,4.900079,9.817243,0.341981,920.070980
...,...,...,...,...,...,...,...,...,...,...,...
204,500.0,59.757821,4.139878,3.885389,0.336196,-0.676045,3.336389,8.788151,9.850903,0.420902,760.480643
205,500.0,61.401245,4.392581,4.332293,0.252633,-0.635730,3.402998,10.553163,9.862172,0.471081,738.620356
206,500.0,64.842379,5.524651,4.029744,-0.785881,-1.457703,3.680124,10.579715,9.847796,0.529103,741.451254
207,500.0,197.253052,4.686967,3.826570,-0.546397,-1.806563,2.907930,10.376503,9.829065,0.456918,887.198699
208,0.0,196.248603,5.051518,3.858845,-1.015878,-1.889710,3.571193,10.206731,9.850763,0.572311,724.569636

In [25]:
del df
gc.collect()
%whos

Variable                         Type              Data/Info
------------------------------------------------------------
ElasticNet                       ABCMeta           <class 'sklearn.linear_mo<...>nate_descent.ElasticNet'>
LinearRegression                 ABCMeta           <class 'sklearn.linear_mo<...>._base.LinearRegression'>
SVR                              ABCMeta           <class 'sklearn.svm._classes.SVR'>
StandardScaler                   type              <class 'sklearn.preproces<...>ng._data.StandardScaler'>
X                                DataFrame         Shape: (209, 10)
XGBRegressor                     type              <class 'xgboost.sklearn.XGBRegressor'>
explained_variance_score         function          <function explained_varia<...>_score at 0x7fdbe36c9440>
gc                               module            <module 'gc' (built-in)>
k                                str               ExplainedVariance
mean_absolute_error              function          <function mean_absolute_error at 0x7fdbe36c89a0>
mean_absolute_percentage_error   function          <function mean_absolute_p<...>_error at 0x7fdbe36c8c20>
mean_squared_error               function          <function mean_squared_error at 0x7fdbe36c8d60>
median_absolute_error            function          <function median_absolute<...>_error at 0x7fdbe36c9260>
metrics                          dict              n=7
model                            XGBRegressor      XGBRegressor(base_score=N<...>_parallel_tree=None, ...)
np                               module            <module 'numpy' from '/ho<...>kages/numpy/__init__.py'>
pd                               module            <module 'pandas' from '/h<...>ages/pandas/__init__.py'>
plt                              module            <module 'matplotlib.pyplo<...>es/matplotlib/pyplot.py'>
r2_score                         function          <function r2_score at 0x7fdbe36c9580>
root_mean_squared_error          function          <function root_mean_squar<...>_error at 0x7fdbe36c8ea0>
sc                               StandardScaler    StandardScaler()
sns                              module            <module 'seaborn' from '/<...>ges/seaborn/__init__.py'>
train_test_split                 function          <function train_test_split at 0x7fdbe36f2f20>
v                                float             0.8640702553734803
x_test                           DataFrame         Shape: (42, 10)
x_test_sc                        ndarray           42x10: 420 elems, type `float64`, 3360 bytes
x_train                          DataFrame         Shape: (167, 10)
x_train_sc                       ndarray           167x10: 1670 elems, type `float64`, 13360 bytes
xgb_pred                         ndarray           42: 42 elems, type `float32`, 168 bytes
y                                Series            Shape: (209,)
y_test                           Series            Shape: (42,)
y_train                          Series            Shape: (167,)

In [28]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 209 entries, 0 to 208
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   payload                209 non-null    float64
 1   total_distance_m       209 non-null    float64
 2   wind_speed_mean        209 non-null    float64
 3   wind_speed_std         209 non-null    float64
 4   wind_x_mean            209 non-null    float64
 5   wind_y_mean            209 non-null    float64
 6   velocity_mag_mean      209 non-null    float64
 7   velocity_mag_max       209 non-null    float64
 8   acceleration_mag_mean  209 non-null    float64
 9   acceleration_mag_std   209 non-null    float64
 10  battery_needed         209 non-null    float64
dtypes: float64(11)
memory usage: 18.1 KB

In [29]:
X = df
y = X.pop("battery_needed")

x_train, x_test, y_train, y_test = train_test_split(
    X, y, test_size= 0.2, random_state= 42)

sc = StandardScaler()

x_train_sc = sc.fit_transform(x_train)
x_test_sc = sc.transform(x_test)

In [30]:
x_train_sc.shape, y_train.shape

((167, 10), (167,))

In [31]:
model = XGBRegressor(
    objective="reg:squarederror",
    n_estimators=500,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1
)
model.fit(x_train_sc, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=True, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=500,
             n_jobs=-1, num_parallel_tree=None, ...)

In [32]:
xgb_pred = model.predict(x_test_sc)

print('xgb')
# print(f'r2  : {r2_score(y_test, xgb_pred)}')
# print(f'RMSE: {root_mean_squared_error(y_test, xgb_pred)}')
metrics = {
    "MAE": mean_absolute_error(y_test, xgb_pred),
    "MSE": mean_squared_error(y_test, xgb_pred),
    "RMSE": root_mean_squared_error(y_test, xgb_pred),
    "R2": r2_score(y_test, xgb_pred),
    "MAPE": mean_absolute_percentage_error(y_test, xgb_pred),
    "MedianAE": median_absolute_error(y_test, xgb_pred),
    "ExplainedVariance": explained_variance_score(y_test, xgb_pred),
}

for k, v in metrics.items():
    print(f"{k:<20}: {v:.6f}")

xgb
MAE                 : 60.193131
MSE                 : 7782.869656
RMSE                : 88.220574
R2                  : 0.863750
MAPE                : 0.076948
MedianAE            : 35.480735
ExplainedVariance   : 0.864070

In [33]:
pd.set_option("display.float_format", "{:.10f}".format)
comparison = pd.DataFrame({
    "Actual": y_test,
    "Predicted": xgb_pred,
})

comparison["delta"] = comparison["Actual"] - comparison["Predicted"]

comparison

             Actual       Predicted           delta
30   928.6805844937  893.2150268555   35.4655576383
171  715.2303003176  699.6381225586   15.5921777590
84   577.4204049518  759.1337890625 -181.7133841107
198  763.3566236314  785.7545776367  -22.3979540053
60   639.9512120362  654.2692871094  -14.3180750732
155   50.4291561514   29.1322879791   21.2968681723
45  1293.8475577725 1317.8518066406  -24.0042488682
181  933.3797536328  869.3434448242   64.0363088085
9    588.9331596962  656.0902709961  -67.1571112998
195  874.6278060942  910.1237182617  -35.4959121675
136 1094.2571706432 1172.2957763672  -78.0386057240
186  983.3208461475 1032.1185302734  -48.7976841260
206  741.4512542887  742.1257324219   -0.6744781332
126  702.6828663386  761.0012207031  -58.3183543645
15   889.6939445020  735.6727905273  154.0211539747
73  1085.4797375589 1038.6677246094   46.8120129495
165  694.8077170098  770.0676879883  -75.2599709784
18   919.6989906530  935.8934936523  -16.1945029993
167 1187.3796667224 1141.6636962891   45.7159704333
93  1179.1016485684 1043.7783203125  135.3233282559
75  1043.5719015307 1050.2412109375   -6.6693094068
55   810.3146529816  864.7591552734  -54.4445022918
147 1432.6108738098 1278.5485839844  154.0622898254
109 1001.4766026733 1141.9592285156 -140.4826258423
108  596.9363988607  635.6069335938  -38.6705347331
142  931.6435719102  914.1842041016   17.4593678086
25   958.8517583960  975.6760864258  -16.8243280297
125 1229.2697450099 1249.7595214844  -20.4897764745
16   792.9512914036  698.7815551758   94.1697362278
172  868.1357125412  877.1349487305   -8.9992361893
191 1140.5117780761  978.0379028320  162.4738752441
69  1156.5895375043 1019.0953979492  137.4941395550
101  908.6933599235  939.1625366211  -30.4691766976
67   823.9219946572  875.7430419922  -51.8210473350
104  729.0206658527  702.4960937500   26.5245721027
132 1003.6067496532  996.9987182617    6.6080313915
207  887.1986992371 1214.3843994141 -327.1857001770
95   762.2860061132  786.4071655273  -24.1211594142
82   954.3950322195  945.8485717773    8.5464604421
159  741.0254141746  720.1856079102   20.8398062644
196 1176.4947694660 1148.6325683594   27.8622011066
162 1037.9689269717 1049.2288818359  -11.2599548643